# Generated by Django 3.0.3 on 2020-02-27 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'db_table': 'author',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'publisher',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('published_date', models.DateField()),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Publisher')),
                ('written', models.ManyToManyField(to='books.Author')),
            ],
            options={
                'db_table': 'book',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='author',
            name='works_for',
            field=models.ManyToManyField(to='books.Publisher'),
        ),
    ]
